"""PR review-comment formatting and idempotent posting.

CodeGuardian posts a single, richly-formatted markdown comment on each
PR summarising the review.  To avoid spamming the PR with duplicate
comments on every push, this module:

* :func:`format_review_comment` — builds the markdown body from a
  review result (verdict, score, issue tables).
* :func:`update_or_post_comment` — finds an existing CodeGuardian
  comment and edits it in place, or creates a new one if none exists.

The comment is marked with a hidden HTML marker so we can reliably
detect it across edits.

Usage::

    from github_tools.comments import format_review_comment, update_or_post_comment

    body = format_review_comment(verdict="APPROVE", score=0.92, issues=[...])
    update_or_post_comment("owner/repo", 42, body)
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from database.models import Issue

__all__ = [
    "COMMENT_MARKER",
    "format_review_comment",
    "find_existing_comment",
    "update_or_post_comment",
]

_log = logging.getLogger(__name__)

# Hidden HTML comment used to identify our bot's comment.  It is
# invisible in the GitHub UI but present in the raw markdown.
COMMENT_MARKER = "<!-- codeguardian-ai-review -->"

# Emoji + label for each severity level, ordered by severity.
_SEVERITY_BADGE = {
    "CRITICAL": "🔴 Critical",
    "HIGH": "🟠 High",
    "MEDIUM": "🟡 Medium",
    "LOW": "🔵 Low",
    "INFO": "⚪ Info",
}

# Emoji for each verdict.
_VERDICT_EMOJI = {
    "APPROVE": "✅",
    "REQUEST_CHANGES": "⚠️",
    "BLOCK_MERGE": "🚫",
    "PENDING": "⏳",
}


def format_review_comment(
    *,
    verdict: str,
    score: float,
    summary: str,
    issues: list[Any] | None = None,
    review_id: int | None = None,
    scanner_findings_count: int = 0,
    agent_findings: dict[str, int] | None = None,
) -> str:
    """Build the markdown body for a PR review comment.

    Parameters
    ----------
    verdict:
        One of ``"APPROVE"``, ``"REQUEST_CHANGES"``, ``"BLOCK_MERGE"``,
        or ``"PENDING"``.
    score:
        Overall risk score in ``[0.0, 1.0]`` (higher = safer).
    summary:
        Human-readable review summary (markdown).
    issues:
        Optional list of :class:`database.models.Issue` (or any object
        with ``agent``, ``severity``, ``title``, ``file``, ``line``,
        ``suggestion`` attributes).  Rendered as a markdown table.
    review_id:
        Optional database review ID (for the "details" link).
    scanner_findings_count:
        Number of static-analysis findings (Semgrep/Bandit/Ruff).
    agent_findings:
        Optional mapping of agent name → finding count (e.g.
        ``{"security": 2, "bug": 0, "performance": 1, ...}``).
        Rendered as a compact breakdown line.

    Returns
    -------
    str
        Complete markdown comment body, including the hidden marker.
    """
    emoji = _VERDICT_EMOJI.get(verdict, "❓")
    score_pct = round(score * 100)

    # Verdict colour bar.
    lines: list[str] = [
        COMMENT_MARKER,
        "",
        f"## {emoji} CodeGuardian AI Review",
        "",
        f"**Verdict:** {verdict}  |  **Risk Score:** {score_pct}/100",
        "",
    ]

    if review_id is not None:
        lines.append(f"> 📋 Review ID: `{review_id}`")
        lines.append("")

    # Summary section.
    if summary:
        lines.append("### Summary")
        lines.append("")
        lines.append(summary)
        lines.append("")

    # Agent findings breakdown.
    if agent_findings:
        parts: list[str] = []
        for agent_name, count in agent_findings.items():
            parts.append(f"{agent_name}: {count}")
        lines.append(
            "🤖 **Agent findings:** " + " · ".join(parts)
        )
        lines.append("")

    # Scanner findings count.
    if scanner_findings_count:
        lines.append(
            f"🔍 **Static analysis:** {scanner_findings_count} finding(s) "
            "from Semgrep / Bandit / Ruff."
        )
        lines.append("")

    # Issues table.
    if issues:
        lines.extend(_format_issues_table(issues))

    lines.append("")
    lines.append(
        "---"
        "\n🤖 *This review was generated by "
        "[CodeGuardian AI](https://github.com) — a multi-agent code "
        "review platform.*"
    )
    return "\n".join(lines)


def _format_issues_table(issues: list[Any]) -> list[str]:
    """Render a list of issues as a markdown table.

    Parameters
    ----------
    issues:
        List of objects with ``agent``, ``severity``, ``title``,
        ``file``, ``line``, ``suggestion`` attributes (e.g.
        :class:`database.models.Issue`).

    Returns
    -------
    list[str]
        Markdown lines forming the table.
    """
    lines = [
        "### Issues Found",
        "",
        "| Severity | Agent | File | Line | Title |",
        "|----------|-------|------|------|-------|",
    ]
    # Sort by severity (critical first).
    severity_order = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3, "INFO": 4}
    sorted_issues = sorted(
        issues,
        key=lambda i: severity_order.get(getattr(i, "severity", "INFO").upper(), 99),
    )
    for issue in sorted_issues:
        sev = getattr(issue, "severity", "INFO").upper()
        badge = _SEVERITY_BADGE.get(sev, sev)
        agent = getattr(issue, "agent", "—")
        file_path = getattr(issue, "file", "—") or "—"
        line = getattr(issue, "line", 0) or "—"
        title = _escape_md(getattr(issue, "title", "—"))
        # Truncate long file paths for readability.
        if len(file_path) > 50:
            file_path = "…" + file_path[-49:]
        lines.append(f"| {badge} | {agent} | `{file_path}` | {line} | {title} |")
    return lines


def _escape_md(text: str) -> str:
    """Escape pipe characters in markdown table cells."""
    return text.replace("|", "\\|").replace("\n", " ")


def find_existing_comment(repo_full_name: str, pr_number: int) -> Any | None:
    """Find an existing CodeGuardian review comment on a PR.

    Scans the PR's issue comments for one containing
    :data:`COMMENT_MARKER`.

    Parameters
    ----------
    repo_full_name:
        ``"owner/repo"``.
    pr_number:
        The PR issue number.

    Returns
    -------
    github.IssueComment.IssueComment | None
        The existing comment, or ``None`` if not found.
    """
    from github_tools.github_api import get_repo

    repo = get_repo(repo_full_name)
    pr = repo.get_pull(pr_number)
    for comment in pr.get_issue_comments():
        if COMMENT_MARKER in (comment.body or ""):
            return comment
    return None


def update_or_post_comment(
    repo_full_name: str,
    pr_number: int,
    body: str,
) -> Any:
    """Update an existing CodeGuardian comment or post a new one.

    This keeps the PR clean — one comment that gets edited on each
    review run, rather than a new comment per push.

    Parameters
    ----------
    repo_full_name:
        ``"owner/repo"``.
    pr_number:
        The PR issue number.
    body:
        The new markdown body (must include :data:`COMMENT_MARKER`).

    Returns
    -------
    github.IssueComment.IssueComment
        The updated or newly created comment.
    """
    existing = find_existing_comment(repo_full_name, pr_number)
    if existing is not None:
        existing.edit(body)
        _log.info(
            "Updated existing review comment on PR #%s in %s",
            pr_number,
            repo_full_name,
        )
        return existing

    # No existing comment — post a new one.
    from github_tools.github_api import post_pr_comment

    post_pr_comment(repo_full_name, pr_number, body)
    _log.info(
        "Posted new review comment on PR #%s in %s",
        pr_number,
        repo_full_name,
    )
    return None
